### ISSUE TITLE
크롤링 데이터에 대한 issue

### ISSUE THREAD

**Issue by dmdwn3979** [twinstae/tripReviewAnalysisSystem#13]
감정분석을 머신러닝하기 위한 단계 중 몇가지 요구 사항 밑 제안 의견 필요가 있기에 적어보겠습니다.
요구사항 
1. 각 데이터에 대한 별점의 긍 부정도의 척도가 필요 할 것 같습니다. 이는 평균값 혹은 수치값이 아닌 사이트의 값 매김(예를 들어 1=worst 2=bad 3=okay 4=good 5=very nice)을 이용한게 적당할 것이라 봅니다. 
2. 이를 이용하여 분류값(긍정 혹은 부정)의 목차값도 txt파일 안에 같이 있으면 좋을 것 같습니다. (이는 학습기에 추가해도 되긴합니다만....)
3. 제목값을 포함 시켜야 할 지에 대한 여부도 궁금합니다.  아무래도 자신의 생각을 가장 간략하게 표현하는, 즉 긍정과 부정이 가장쉽게 나타나는 곳이 제목이라고 생각되기에 당연히 해야 한다고 생각이 듭니다만, 이럴 경우 데이터는 제목과 본문을 통합해도 무관하다고 생각듭니다.

**Comment by dmdwn3979** [comment]
참고로 저는 부정값을 3점 까지라고 생각이 듭니다. 많은 리뷰들이 4점 혹은 5점을 긍정, 그리고 3점 이하값은 거의 주지 않고 있습니다. (정말 부정이라고 생각되지 않는이상) 이에 3점 또한 나쁘지않다, 잘 모르겠다 식의 반응이기에 부정이라고 생각듭니다.

**Comment by twinstae** [comment]
1. 말씀하시는 게 이해가 잘 안 가는데, 각 리뷰에 별점이 필요하시다는 건가요? 별점은 이미 같이 크롤링 되어 있으니 그건 아닐 테고... 사이트의 값별 매김이면 또 별점 이야기하시는 건가 싶고요. 목차값은 어떤 걸 이야기하시는 건가요?

2. 제목값을 포함시킬지는, 지도학습 데이터를 만들어서 검증하면 될 것 같습니다. 특정 예측에 본문 내용보다 제목이 더 강력한 영향을 끼친다면, 제목은 짧더라도 가중치를 둬야겠죠. 예를 들어 제가 덕수궁 데이터를 살펴봤는데 문지기guard가 chaging교대하는 모습을 인상 깊게 보신 분들이 많았고 그게 제목에도 반영되더라고요.

3. 그리고 이슈에 담당자assignees, labeld, projects, Milestone을 설정해주세요! 제가 올린 다른 이슈 참고하시면 어떻게 매기는지 알 수 있으실 거에요.

**Comment by dmdwn3979** [comment]
1번에 관해서는 간단하게 긍정과 부정의 이분법적인 매김법에 관한 것입니다! 이 글이 부정적이다, 혹은 긍정적이다 라는것을 지도학습 시키기 위해서는 각 코맨트가 긍정인지 부정인지 라벨링이 필요하고 그 척도가 별점인데 그것을 정하자 입니다. 많은 예시들도 3점이하는 부정 초과는 긍정, 이런식으로 하니까요

**Comment by twinstae** [comment]
별점 데이터가 있으니 가공하셔서 머신러닝에 활용하시면 되겠네요. 이슈는 닫을까요?
