### ISSUE TITLE
파일의 내용이 저장되지 않습니다.

### ISSUE THREAD

**Issue by JSH-data** [twinstae/tripReviewAnalysisSystem#16]
태희씨한테 도움요청드립니다!
크롤러 실행시 원만하게 진행이 되는데 막상 파일을 실행시키면 원하는 정보가 제대로 담겨있지 않습니다. 
혹시 어디가 잘못된점이 있는지 지적해주시면 정말로 감사하겠습니다!

**Comment by twinstae** [comment]
크롤러에서 review text 안에 여러 문단을 <br>로 처리하니 string으로 변환하지 못하는 문제 였습니다. 현재 수정하였고, 데이터 다시 크롤링하는 중 입니다. 이슈 닫겠겠습니다.
