### ISSUE TITLE
리뷰 결측치

### ISSUE THREAD

**Issue by twinstae** [twinstae/tripReviewAnalysisSystem#18]
### 문제
데이터를 검토해보니 북한산을 비롯한 몇몇 데이터가 크롤링이 안 되어 있더군요. 크롤러에 문제가 있었던 모양인데, 원인은 정확하게 모르겠습니다.

### 사용자 스토리
북한산을 비롯한 중요한 여행지에 대한 데이터를 확보합니다.

### 다음행동
크롤러를 간단히 개조해서 특정한 여행지에 대한 리뷰만 긁어올 수 있게 하면 될 것 같습니다.
바로 그 여행지에 대한 페이지를 열어서, 리뷰만 긁게 만들면 되는 거지요.

**Comment by JSH-data** [comment]
확인했습니다! 한 번 고쳐서 저장해보겠습니다.!

**Comment by twinstae** [comment]
완료
