### ISSUE TITLE
크롤링 데이터에 대한 분류값 요청

### ISSUE THREAD

**Issue by dmdwn3979** [twinstae/tripReviewAnalysisSystem#20]
### **현재 데이터**
현재 데이터는 star_point, title, text, date of experience 의 항몫으로 주어져 있습니다.

### **요구 사항**
데이터에 관한 분류값이 필요합니다.
데이터프레임에 Column 값이 아니더라도 인덱싱 같이 attraction 에 대한 분류 정보값이 포함 되어 있으면 좋을 것 같습니다.

### **추가 사항**

1. 일부 데이터에 결측치가 아직 있습니다. 현재 코드에서 명사만을 뽑았을 때 결측치 값이 2~3개 보입니다. (명사를 제외한 댓글만 있을 수 있음) 
이는 현재 예외처리를 하여 큰 문제는 아닐 수 있습니다.

2. 연관도 분석에 관하여 연관 검색어(See also) 혹은 추천 여행지를 만드려고 합니다. 이에 따라 앞선 분류값이(연관 검색어는 필요, 추천 여행지는 불필요) 요구 되기도 합니다.

**Comment by twinstae** [comment]
지금 따로 되어 있으니, 두 데이터를 합치면 되긴 하는데요. JOIN이나 데이터 프레임 함수로 만들면 될 것 같습니다.

**Comment by twinstae** [comment]
완료
