### ISSUE TITLE
이동수단, 시간 데이터 수집

### ISSUE THREAD

**Issue by JSH-data** [twinstae/tripReviewAnalysisSystem#32]
군집화를 이용해서 어트랙션간의  위치정도를 파악했기 때문에

이를 활용해 사용자에게 유용한 정보를 주려고 합니다.

1. 4가지의 군집간의 이동 수단, 시간

2. 군집화의 중간 지점과 주변 어트랙션의 이동 수단, 시간

**Comment by twinstae** [comment]
어떤 경로를 구해야 할지... 최소 경로 알고리즘을 구축하자. -> 구글 지도 라이브러리로 크롤링.

**Comment by twinstae** [comment]
결과물 (a, b) 튜플 쌍을 만들어주시면 됩니다 (180 * 179 / 2... 는 안 된다. )

**Comment by dmdwn3979** [comment]
최소 경로 알고리즘을 사용하는 이유에 대한 이해가 필요할 것 같습니다.

**Comment by twinstae** [comment]
우리가 원하는 건 경로를 나타내는 여행지 쌍들입니다. 우리는 다음 여행지 추천과 길 안내를 위해 이 데이터를 사용합니다.

이는 모두 180 * 179 / 2가지가 가능합니다. 하지만...

1. 이 모든 데이터를 크롤링하는데 시간이 너무 많이 걸립니다.
2. 사용자에게 이 모든 가능성을 추천해줄 필요도 없습니다. 대부분의 사용자는 가까이 있는 여행지끼리 돌아다니는 경우가 많을 겁니다.

따라서 저희는 지역으로 여행지를 분할했습니다. 그래서 같은 지역 내에 있는 여행지 간의 쌍만 고려하려 했습니다. 지역 간에 이동할 때는 중심 허브를 통해 이동하도록 하려했습니다. 예를 들어 40개 정도씩 4개로 나눈다면 가능한 조합의 수가 1/4로 줄어듭니다.

문제는 지역과 지역의 경계에 있는 여행지들입니다. 이게 제가 최근접 쌍 찾기 알고리즘이 떠오른 게 이 부분인데요...
https://adrian0220.tistory.com/44
예를 들어 a에서 b로 가는데 걸어서 10분이면 되는데, 각각 빨강 지역과 초록 지역에 속해있다고 합시다. 이 둘은 다른 지역이기 때문에, a에서 빨강의 허브로 간 다음, 초록의 허브로 이동해서 b로 이동하는... 매우 비효율적인 경로를 추천하게 됩니다.

그래서 같은 지역 내에 있는 쌍 뿐만 아니라, 각 여행지에서 가까운 거리에 있는 여행지들의 쌍을 구하고자 하는 겁니다.

이 알고리즘을 대충 구상하면 다음과 같습니다. 
여행지 180개의 좌표와, 지역을 받아온다.(군집화 코드 그대로 이용)
같은 지역 내에 있는 여행지 간의 쌍을 만든다.

-> (지역과 지역 경계에서 일정 거리 내에 있는 혹은) 모든 쌍에 대하여 거리를 계산한다.

-> 일정 거리 내에 있지만, 다른 지역에 있는 여행지와의 쌍을 추출한다. (500미터 이내, 1.5키로 이내)

**Comment by dmdwn3979** [comment]
이해한 바가 맞다면
1. 같은 군집 내의 중심 허브지역에서 이동경로 추천
2. 경계선에서의 이동경로 추천
발생하는 문제-----> 2번 에서 기존의 생각대로 한다면 (1번) 경계선에서의 여행지는 허브 중심으로 짜게 되므로 문제가 생긴다
인데
약간의 혼동이 아직 남아있어 일단 구상대로 코드를 구현 후 올려보고 수정하는 방향으로 진행 해 보겠습니다
