### ISSUE TITLE
리뷰 별 단어 등장빈도, 긍정/부정 정도 분석

### ISSUE THREAD

**Issue by twinstae** [twinstae/tripReviewAnalysisSystem#4]
## 요구사항
리뷰에 등장하는 단어를 등장빈도와, 별점이나 감정사전 분석에 따라 부정적인 단어인지, 긍정적인 단어인지 평가해주세요.

## 사용자 스토리 (가치, 이유)
결과를 토대로 단어별 가중치를 둔 워드 클라우드를 만들겠습니다.
(긍정적인 단어는 금색, 부정적인 단어는 적갈색)

### 입력
상위 180개 즐길거리의 리뷰 원시 데이터
 - 즐길거리 마다 하나의 csv 형식 파일.
 - 데이터 형태는 #3 이슈를 봐주세요.
### 출력 (원하는 결과물)
 - 각 즐길거리 별 csv 형식 파일.
 - 데이터 형태
     - 제목. "즐길거리 이름_분류_긍정부정 단어 리스트.csv"
         - 예시. "Seoul Metro_MASS TRANSPORTATION SYSTEMS_긍정부정 단어 리스트.csv"
     - 각 행 : 단어 하나. 빈도순으로 정렬.
     - 1열. 단어 이름
     - 2열. 단어 등장 빈도
     - 3열. 평균 별점 (1.0~5.0)
     - 4열. 긍정 감정 (0.0~1.0)

**Comment by dmdwn3979** [comment]
현재 진행도: 즐길거리 1개에 대한 (58개의 댓글) 데이터를 이용한 머신러닝
1,2 코드에 포함(출력은 x)
3. 평균별점 코드 미처리
4. 긍정 감정 처리 완료

결과물: 머신러닝 데이터의 저장

추후 행동: 결과물을 이용한 처리기 생성, 더욱 많은 데이터 이용한 분류기 생성, 이해도를 위한 단어와 빈도 그리고 별점의 평균값 생성해보기

**Comment by twinstae** [comment]
완료
